services:
  database:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=donpark
      - MYSQL_PASSWORD=donpark
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/backup:/var/lib/mysql
    networks:
      - net

  application:
    depends_on:
      - database
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/test?useSSL=false
      SPRING_DATASOURCE_USERNAME: donpark
      SPRING_DATASOURCE_PASSWORD: donpark
    networks:
      - net

networks:
  net:
