server:
  port: 9090
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/test
    username: donpark
    password: donpark
