server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/test
    username: donpark
    password: donpark